sentence: ipmat
ipmat: ipadv CONJ PU pp pp NPOB1 VB PU
ipadv: ipadv CONJ PU pp VB P | pp pp VB P | pp NPOB1 VB P
pp: np P
np: NPR | ipemb N | iprel N | pp N | N | D N
ipemb: ipadv SCON PU cptht VB | VB
iprel: ADJI
cptht: ipsub P
ipsub: pp NPOB1 VB AX
CONJ: "n"
PU: "――" | "。" | "、"
NPOB1: "nがn" | "nをn" | "nにn"
VB: "ある" | "しなっ" | "ひらつい" | "動い" | "思う" | "眺（なが）め" | "なり" | "煽（あお）る"
P: "たり" | "は" | "が" | "に" | "ながら" | "と" | "の" | "を"
NPR: "良平"
N: "事" | "線路" | "裾（すそ）" | "よう" | "車台" | "袢天（はんてん）" | "けしき" | "土工"
SCON: "n"
ADJI: "細い"
AX: "たい"
D: "そんな"
%import common.WS
%ignore WS
